apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: sample-web-flask
    newName: image-registry.openshift-image-registry.svc:5000/flask-app-dev/sample-web-flask
    newTag: 09rew34
